Update VakifBankPos.php
mewebstudio/pos pull request #44
Opened 2021-11-26 07:43 UTC by zeydduran

Vakıfbank InstallmentCount değerini "0" yada "1" olarak kabul etmez.
Taksit varsa 1' den büyük bir değer gönderilmelidir aksi taktirde bu değer gönderilmemelidir.

2021-11-26 09:04 UTC, nuryagdym requested changes
Tesekkurler elinize saglik.

Bu iki guncellemeler unit'testi buyuk ihtmalle fail eder. Mumkunse Unit'testlerde de gereken guncellemeleri yapar misiniz.

2021-11-26 09:04 UTC, nuryagdym commented on src/Gateways/VakifBankPos.php
> +        if ($this->order->installment > 1) {
Ayni guncelleme **NumberOfInstallments** bu alan icin gerekiyor, onu da ekler misiniz:
![image](https://user-images.githubusercontent.com/26792980/143554610-d305a247-5e15-4600-9f75-810af3cdc2c9.png)
calisiyor mi diye testte  etseniz guzel olur.

2021-11-26 09:27 UTC, zeydduran commented on src/Gateways/VakifBankPos.php
> +        if ($this->order->installment > 1) {
Şu an bi projemde üzerinde çalışıyorum. Sorunsuz çalışır hale geldiğinde tekrar PR açacağım

2021-12-04 16:26 UTC, nuryagdym commented
sorun PR #47'de duzeltildi, bu PR'i kapatiyorum

2021-12-04 16:26 UTC, closed without merging